"""remove_company_brand_name

Revision ID: 094ce3ca428a
Revises: adee4f597e6b
Create Date: 2026-03-06 12:49:36.014915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094ce3ca428a'
down_revision: Union[str, Sequence[str], None] = 'adee4f597e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'brand_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('brand_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
