"""add target problem to call summary

Revision ID: 0e7e9d0ac7c5
Revises: bdb309aa2f09
Create Date: 2026-03-09 10:49:10.869961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7e9d0ac7c5'
down_revision: Union[str, Sequence[str], None] = 'bdb309aa2f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_summaries', sa.Column('target_problem', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_summaries', 'target_problem')
    # ### end Alembic commands ###
