"""implement_cascading_deletes

Revision ID: 724174dfd41a
Revises: b3e97c43c306
Create Date: 2026-03-07 05:51:52.925650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '724174dfd41a'
down_revision: Union[str, Sequence[str], None] = 'b3e97c43c306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_brand_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_company_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_organisation_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'organisations', ['organisation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_organisation_id_fkey'), 'users', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('users_company_id_fkey'), 'users', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_brand_id_fkey'), 'products', 'brands', ['brand_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
